server:
  port: 3791 # 실행될 포트 설정

spring:
  application:
    name: unitalk

  # 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 데이터베이스 드라이버 클래스 이름 설정
    url: jdbc:mysql://localhost:3306/unitalk?serverTimezone=Asia/Seoul # 데이터베이스 연결 URL 설정
    username: jt001 # 데이터베이스 사용자 이름 설정
    password: 1234 # 데이터베이스 비밀번호 설정

  # jpa 설정
  jpa:
    database: mysql # MySQL로 설정
    #database-platform: org.hibernate.dialect.MySQL8Dialect 버전이 높아지며 명시할 필요 없음
    generate-ddl: true # DDL 자동 생성
    show-sql: true # SQL 쿼리를 출력
    open-in-view: false # 비활성화하여 성능 최적화
    hibernate:
      ddl-auto: update # 애플리케이션 시작 시 데이터베이스 스키마 설정
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅
        use_sql_comments: true # SQL 쿼리 주석 추가
        default_batch_fetch_size: 100 # 기본 배치 가져오기 크기를 100으로 설정

  # 파일 설정(파일크기)
  servlet:
    multipart:
      max-file-size: 50MB # 업로드 가능한 파일의 최대 크기 설정
      max-request-size: 50MB # 업로드 요청의 최대 크기 설정

  # devtools 설정
  devtools:
    livereload:
      enabled: true # 브라우저 자동 새로고침 활성화
    restart:
      enabled: false # 자동 재시작 비활성화

  # Jackson이 Hibernate 프록시를 직렬화하지 않도록 설정
  # Hibernate 프록시는 지연 로딩(Lazy Loading) 기능을 지원하기 위해 Hibernate가 생성하는 객체
  # 프록시 객체가 참조하는 객체와의 관계로 인해 순환 참조가 발생할 수 있습니다. 이로 인해 직렬화 도중 무한 루프가 발생할 수 있는데 이를 방지
  jackson:
    serialization:
      fail-on-empty-beans: false
