server:
  port: 3791

spring:
  application:
    name: unitalk

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unitalk?serverTimezone=Asia/Seoul
    username: jt001
    password: 1234

jpa:
  database: mysql
  #database-platform: org.hibernate.dialect.MySQL8Dialect 버전이 높아지며 명시할 필요 사라짐
  generate-ddl: true
  show-sql: true
  open-in-view: false
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 100

  # 파일 설정(파일크기)
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  # devtools 설정 (파일크기)
  devtools:
    livereload:
      enabled: true # 브라우저 자동 새로고침 활성화
    restart:
      enabled: false # 자동 재시작 비활성화