server:
  port: 3791

spring:
  application:
    name: unitalk

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unitalk?serverTimezone=Asia/Seoul
    username: jt001
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    # show-sql: true # DDL 출력